# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: gittyleaks
        name: Run GittyLeaks
        entry: uv run gittyleaks
        language: python
        pass_filenames: false

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: bash -c "PYTHONPATH=src uv run -m pytest"
        language: system
        pass_filenames: false