services:

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./requirements/prometheus/config:/etc/prometheus/
    networks:
      - monitoring
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    env_file:
      - ./requirements/grafana/config.monitoring
    networks:
      - monitoring
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./requirements/grafana/provisioning/:/etc/grafana/provisioning/

networks:
  monitoring:
    name: monitoring
