apiVersion: v1
kind: Service
metadata:
  namespace: salary-prediction
  name: salary-prediction-api
spec:
  type: NodePort
  selector:
    app: salary-prediction-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000