apiVersion: v1
kind: PersistentVolume
metadata:
  name: salary-prediction-models
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/salary-prediction-api/models
  storageClassName: