apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: salary-prediction
  name: models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
  resources:
    requests:
      storage: 1Gi