# .github/workflows/run.yml
name: Run Container

on:
  workflow_dispatch:

env:
  IMAGE_NAME: 'salary-prediction-api'
  DATA_DIR: './src/data'
  MODELS_DIR: './src/models'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (if needed)
        run: |
          if ! docker images | grep -q $IMAGE_NAME; then
            echo "Image not found, building first..."
            chmod +x src/api/build_image.sh
            ./src/api/build_image.sh
          fi

      - name: Run container
        run: |
          echo "Running salary-prediction-api container"
          chmod +x src/api/run_container.sh
          ./src/api/run_container.sh

      - name: Check container status
        run: docker ps
